### ISSUE TITLE
Demo URL is broken

### ISSUE THREAD

**Issue by ungoldman** [editdata/data-grid#2]
http://about.editdata.org/data-grid/ -> http://editdata.org/data-grid/ -> surge.sh 404 😞

**Comment by sethvincent** [comment]
I knew I'd missed something in the url renaming.

It can be found here for now: http://editdata.github.io/data-grid/

**Comment by ungoldman** [comment]
FYI Github repo description still says: http://about.editdata.org/data-grid/

😁

**Comment by sethvincent** [comment]
:heart:

**Comment by ungoldman** [comment]
💯
